---
- name: Обновление списка пакетов
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags: common

- name: Установка базовых пакетов
  apt:
    name:
     - curl
     - wget
     - git
     - python3-pip
     - software-properties-common
     - gnupg
     - lsb-release
    state: present
  tags: common

- name: Настройка часового пояса
  timezone:
    name: "{{ timezone }}"
  tags: common

- name: Настройка hostname
  hostname:
    name: "{{ inventory_hostname }}"
  tags: common