---
# Основные переменные
ansible_user: safalkon
ansible_ssh_private_key_file: "~/.ssh/id_ed25519"
ansible_python_interpreter: "/usr/bin/python3"
#ansible_become: true

# Настройки времени
timezone: "Europe/Moscow"

# Настройки сети
internal_network: "10.0.0.0/16"

# Пароли (в продакшене используйте ansible-vault!)
postgresql_zabbix_password: "ZabbixSecurePass123!"
elastic_password: "ElasticSecurePass123!"
kibana_password: "KibanaSecurePass123!"

# Версии ПО
elasticsearch_version: "8.11.0"
kibana_version: "8.11.0"
filebeat_version: "8.11.0"
zabbix_version: "6.0"

# Мониторинг
# zabbix_server_ip: "{{ hostvars[groups['zabbix_server'][0]]['ansible_host'] }}"
zabbix_server_port: 10051
zabbix_admin_password: "zabbix"

# ELK Stack
elasticsearch_host: "{{ hostvars[groups['elasticsearch_server'][0]]['ansible_host'] }}"
elasticsearch_port: 9200
kibana_host: "{{ hostvars[groups['kibana_server'][0]]['ansible_host'] }}"
kibana_port: 5601

# Zabbix server details
zabbix_server_fqdn: "{{ groups['zabbix_server'][0] }}"
zabbix_server_ip: "{{ hostvars[groups['zabbix_server'][0]]['ansible_default_ipv4']['address'] }}"

# Zabbix agent settings (будет использоваться в роли)
zabbix_agent_server: "127.0.0.1,{{ zabbix_server_fqdn }},{{ zabbix_server_ip }}"
zabbix_agent_serveractive: "{{ zabbix_server_fqdn }}"
zabbix_agent_listenip: "0.0.0.0"
zabbix_agent_listenport: 10050